// product line actions
export const ADD_TO_PRODUCT_LINE = "ADD_TO_PRODUCT_LINE"
export const REMOVE_FROM_PRODUCT_LINE = "REMOVE_FROM_PRODUCT_LINE"
export const EDIT_PRODUCT = "EDIT_PRODUCT"

// shopping cart actions
export const ADD_TO_SHOPPING_CART = "ADD_TO_SHOPPING_CART"
export const REMOVE_FROM_SHOPPING_CART = "REMOVE_FROM_SHOPPING_CART"
export const CHANGE_QUANTITY = "CHANGE_QUANTITY"
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY"

// discount actions
export const ADD_DISCOUNT = "ADD_DISCOUNT"
export const REMOVE_DISCOUNT = "REMOVE_DISCOUNT"